# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            OhMe
tagline:          
description:      
url:              http://ookmie.github.io
baseurl:          /

author:
#  name:           'ookmie'
#  url:            http://ookmie.github.io

paginate:         5

# Custom vars
# version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
